services:
  web:
    build: .
    image: test:llamafile
    entrypoint: "/bin/sh"
    stdin_open: true
    tty: true
    command: bash -c "./llava-v1.5-7b-q4.llamafile --server --nobrowser & ngrok http 8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
